services:
    traefik:
        image: traefik:v3.0.1
        container_name: traefik
        command:
            # Enables the web UI and tells Traefik to listen to docker
            - "--api.dashboard=true"
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--entrypoints.web.address=:80"
            - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
            - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
            - "--entrypoints.websecure.address=:443"
            - "--certificatesResolvers.le.acme.email=${EMAIL}"
            - "--certificatesResolvers.le.acme.storage=/etc/traefik/acme.json"
            - "--certificatesResolvers.le.acme.dnsChallenge.provider=infomaniak"
            - "--certificatesResolvers.le.acme.dnsChallenge.delayBeforeCheck=10"
        ports:
            - 80:80
            - 443:443
        expose:
            - 8080
        volumes:
            # So that Traefik can listen to the Docker events
            - /var/run/docker.sock:/var/run/docker.sock
            - ${BASE_PATH}/traefik/:/etc/traefik/
        environment:
            - INFOMANIAK_ACCESS_TOKEN
            - FQDN
        labels:
            - traefik.http.routers.traefik.rule=Host(`traefik.${FQDN}`)
            - traefik.http.routers.traefik.tls=true
            - traefik.http.routers.traefik.tls.certresolver=le
            - traefik.http.routers.traefik.tls.domains[0].main=${FQDN}
            - traefik.http.routers.traefik.tls.domains[0].sans=*.${FQDN}
            - traefik.http.services.traefik.loadbalancer.server.port=8080
        restart: unless-stopped

    portainer:
        image: portainer/portainer-ce:2.20.2
        container_name: portainer
        expose:
            - 9000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ${BASE_PATH}/portainer:/data
        labels:
            - traefik.http.routers.portainer.rule=Host(`portainer.${FQDN}`)
            - traefik.http.routers.portainer.tls=true
            - traefik.http.routers.portainer.tls.certresolver=le
            - traefik.http.routers.portainer.tls.domains[0].main=${FQDN}
            - traefik.http.routers.portainer.tls.domains[0].sans=*.${FQDN}
            - traefik.http.services.portainer.loadbalancer.server.port=9000
        restart: unless-stopped

    prowlarr:
        image: lscr.io/linuxserver/prowlarr:1.17.2
        container_name: prowlarr
        volumes:
            - ${BASE_PATH}/prowlarr:/config
        environment:
            - PUID
            - PGID
            - TZ
        labels:
            - traefik.http.routers.prowlarr.rule=Host(`prowlarr.${FQDN}`)
            - traefik.http.routers.prowlarr.tls=true
            - traefik.http.routers.prowlarr.tls.certresolver=le
            - traefik.http.routers.prowlarr.tls.domains[0].main=${FQDN}
            - traefik.http.routers.prowlarr.tls.domains[0].sans=*.${FQDN}
        expose:
            - 9696
        restart: unless-stopped

    sonarr:
        image: lscr.io/linuxserver/sonarr:4.0.4
        container_name: sonarr
        volumes:
            - ${BASE_PATH}/sonarr:/config
            - /volume1/Media:/media
        environment:
            - PUID
            - PGID
            - TZ
        labels:
            - traefik.http.routers.sonarr.rule=Host(`sonarr.${FQDN}`)
            - traefik.http.routers.sonarr.tls=true
            - traefik.http.routers.sonarr.tls.certresolver=le
            - traefik.http.routers.sonarr.tls.domains[0].main=${FQDN}
            - traefik.http.routers.sonarr.tls.domains[0].sans=*.${FQDN}
        expose:
            - 8989
        restart: unless-stopped

    bazarr:
        image: lscr.io/linuxserver/bazarr:1.4.2
        container_name: bazarr
        volumes:
            - ${BASE_PATH}/bazarr:/config
            - /volume1/Media:/media
        environment:
            - PUID
            - PGID
            - TZ
        labels:
            - traefik.http.routers.bazarr.rule=Host(`bazarr.${FQDN}`)
            - traefik.http.routers.bazarr.tls=true
            - traefik.http.routers.bazarr.tls.certresolver=le
            - traefik.http.routers.bazarr.tls.domains[0].main=${FQDN}
            - traefik.http.routers.bazarr.tls.domains[0].sans=*.${FQDN}
        expose:
            - 6767
        restart: unless-stopped

    radarr:
        image: lscr.io/linuxserver/radarr:5.6.0
        container_name: radarr
        volumes:
            - ${BASE_PATH}/radarr:/config
            - /volume1/Media:/media
        environment:
            - PUID
            - PGID
            - TZ
        labels:
            - traefik.http.routers.radarr.rule=Host(`radarr.${FQDN}`)
            - traefik.http.routers.radarr.tls=true
            - traefik.http.routers.radarr.tls.certresolver=le
            - traefik.http.routers.radarr.tls.domains[0].main=${FQDN}
            - traefik.http.routers.radarr.tls.domains[0].sans=*.${FQDN}
        expose:
            - 7878
        restart: unless-stopped

    recyclarr:
        container_name: recyclarr
        image: ghcr.io/recyclarr/recyclarr:6.0.2
        user: ${PUID}:${PGID}
        environment:
            - TZ
        volumes:
            - ${BASE_PATH}/recyclarr:/config
        restart: unless-stopped

    qbittorrent:
        container_name: qbittorrent
        image: lscr.io/linuxserver/qbittorrent:4.6.4
        environment:
            - PUID
            - PGID
            - TZ
            - DOCKER_MODS=ghcr.io/gabe565/linuxserver-mod-vuetorrent
        volumes:
            - ${BASE_PATH}/qbittorrent:/config
            - /volume1/Media/Downloads:/media/Downloads
        ports:
            - 6881:6881
            - 6881:6881/udp
        labels:
            - traefik.http.routers.qbittorrent.rule=Host(`torrent.${FQDN}`)
            - traefik.http.routers.qbittorrent.tls=true
            - traefik.http.routers.qbittorrent.tls.certresolver=le
            - traefik.http.routers.qbittorrent.tls.domains[0].main=${FQDN}
            - traefik.http.routers.qbittorrent.tls.domains[0].sans=*.${FQDN}
            - traefik.http.services.qbittorrent.loadbalancer.server.port=8080
        expose:
            - 8080
        restart: unless-stopped

    tautulli:
        image: lscr.io/linuxserver/tautulli:2.14.2
        container_name: tautulli
        volumes:
            - ${BASE_PATH}/tautulli:/config
        environment:
            - PUID
            - PGID
            - TZ
        labels:
            - traefik.http.routers.tautulli.rule=Host(`tautulli.${FQDN}`)
            - traefik.http.routers.tautulli.tls=true
            - traefik.http.routers.tautulli.tls.certresolver=le
            - traefik.http.routers.tautulli.tls.domains[0].main=${FQDN}
            - traefik.http.routers.tautulli.tls.domains[0].sans=*.${FQDN}
        expose:
            - 8181
        restart: unless-stopped

    calibre-web:
        image: lscr.io/linuxserver/calibre-web:0.6.21
        container_name: calibre-web
        volumes:
            - ${BASE_PATH}/calibre-web:/config
            - /volume1/Media/Books:/media/Books
        environment:
            - PUID
            - PGID
            - TZ
        labels:
            - traefik.http.routers.calibre-web.rule=Host(`calibre.${FQDN}`)
            - traefik.http.routers.calibre-web.tls=true
            - traefik.http.routers.calibre-web.tls.certresolver=le
            - traefik.http.routers.calibre-web.tls.domains[0].main=${FQDN}
            - traefik.http.routers.calibre-web.tls.domains[0].sans=*.${FQDN}
        expose:
            - 8083
        restart: unless-stopped

    home-assistant:
        image: homeassistant/home-assistant:2024.5
        container_name: home-assistant
        volumes:
            - ${BASE_PATH}/home-assistant:/config
        environment:
            - TZ
        network_mode: host
        expose:
            - 8123
        restart: unless-stopped

    redis:
        image: redis:7.2.4
        container_name: redis
        restart: unless-stopped
        volumes:
            - ${BASE_PATH}/redis:/data

    paperless:
        image: ghcr.io/paperless-ngx/paperless-ngx:2.8.6
        container_name: paperless
        depends_on:
            - redis
        volumes:
            - ${BASE_PATH}/paperless/data:/usr/src/paperless/data
            - ${BASE_PATH}/paperless/media:/usr/src/paperless/media
            - ${BASE_PATH}/paperless/export:/usr/src/paperless/export
            - ${BASE_PATH}/paperless/consume:/usr/src/paperless/consume
        environment:
            - PAPERLESS_REDIS
            - USERMAP_UID
            - USERMAP_GID
            - PAPERLESS_URL
            - PAPERLESS_TIME_ZONE
            - PAPERLESS_OCR_LANGUAGE
        labels:
            - traefik.http.routers.paperless.rule=Host(`paperless.${FQDN}`)
            - traefik.http.routers.paperless.tls=true
            - traefik.http.routers.paperless.tls.certresolver=le
            - traefik.http.routers.paperless.tls.domains[0].main=${FQDN}
            - traefik.http.routers.paperless.tls.domains[0].sans=*.${FQDN}
        expose:
            - 8000
        restart: unless-stopped

    actual_server:
        image: ghcr.io/actualbudget/actual-server:24.5.0
        container_name: actual
        volumes:
            - ${BASE_PATH}/actual:/data
        labels:
            - traefik.http.routers.actual.rule=Host(`actual.${FQDN}`)
            - traefik.http.routers.actual.tls=true
            - traefik.http.routers.actual.tls.certresolver=le
            - traefik.http.routers.actual.tls.domains[0].main=${FQDN}
            - traefik.http.routers.actual.tls.domains[0].sans=*.${FQDN}
        expose:
            - 5006
        restart: unless-stopped

    adguard:
        image: adguard/adguardhome:v0.107.49
        container_name: adguard
        ports:
            - 53:53/udp
        volumes:
            - ${BASE_PATH}/adguard/work:/opt/adguardhome/work
            - ${BASE_PATH}/adguard/conf:/opt/adguardhome/conf
        labels:
            - traefik.http.routers.adguard.rule=Host(`adguard.${FQDN}`)
            - traefik.http.routers.adguard.tls=true
            - traefik.http.routers.adguard.tls.certresolver=le
            - traefik.http.routers.adguard.tls.domains[0].main=${FQDN}
            - traefik.http.routers.adguard.tls.domains[0].sans=*.${FQDN}
            - traefik.http.services.adguard.loadbalancer.server.port=3000
        restart: unless-stopped

networks:
    default:
        driver: bridge
